name: movies_storage_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: 2.0.4
  hive_flutter: 1.1.0
  shared_preferences: 2.0.6
  path_provider: 2.0.2
  dio: 4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.3
  http: ^0.13.3
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  material_floating_search_bar: ^0.3.4
  build_runner: ^2.0.6
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Questrial
      fonts: 
        - asset: assets/fonts/Questrial/Questrial-Regular.ttf
    - family: Press_Start_2P
      fonts: 
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

  assets:
    - assets/images/
